### ISSUE TITLE
Readme.md has no table of contents

### ISSUE THREAD

**Issue by philroyer** [kirbinator/redbot#1]
As I'm a fan of skimming tables of contents to get a general understanding of a repo, I would like to see this added.

**Comment by kirbinator** [comment]
it's sounds really difficult!

**Comment by philroyer** [comment]
Super easy actually! Add me as a contributor and I can do it in 2 minutes!

**Comment by kirbinator** [comment]
You are a super programmer. Redbot thanks you!
